#pragma once

#include <cstdint>
#include <functional>
#include <string>
#include <vector>

#include "esphome/core/automation.h"
#include "esphome/core/component.h"
#include "esphome/core/helpers.h"
#include "esphome/components/http_request/http_request.h"
#include "esphome/components/sensor/sensor.h"
#include "esphome/components/time/real_time_clock.h"
#ifdef USE_TEXT_SENSOR
#include "esphome/components/text_sensor/text_sensor.h"
#endif

namespace esphome::influxdb {

/// Uploads sensor states to InfluxDB v2 as line protocol, one line per measurement.
///
/// Sensors are registered at codegen time with their measurement and field key. A sensor is
/// only included in an upload when it has produced a filtered value since it was last uploaded,
/// so a sensor that stops reporting drops out of the payload instead of re-sending its last
/// value forever. Uploads go through the http_request component (which owns the socket
/// timeout and task-watchdog handling); transient failures are retried from the scheduler
/// without blocking the main loop.
class InfluxDB : public Component {
 public:
  // Must match MAX_MEASUREMENTS in __init__.py
  static constexpr size_t MAX_MEASUREMENTS = 4;
  static constexpr uint32_t UPDATE_INTERVAL_NEVER = UINT32_MAX;
  static constexpr uint8_t MAX_ATTEMPTS = 3;
  static constexpr uint32_t RETRY_BACKOFF_MIN_MS = 2000;
  static constexpr uint32_t RETRY_BACKOFF_RANGE_MS = 3000;

  void setup() override;
  void dump_config() override;
  float get_setup_priority() const override { return setup_priority::AFTER_CONNECTION; }

  /// Upload every configured sensor that has a fresh value.
  void publish() { this->publish_(nullptr); }
  /// Upload only the given sensors (a subset of the configured ones).
  void publish(const std::vector<sensor::Sensor *> &only) { this->publish_(&only); }

  void set_host(const char *host) { this->host_ = host; }
  void set_port(uint16_t port) { this->port_ = port; }
  /// Compiled-in token; may be empty when every unit is provisioned at runtime.
  void set_token(const char *token) { this->token_ = token; }
  /// Token provisioned at runtime (the caller keeps it, e.g. in a restored global). Takes
  /// precedence over the compiled-in one; an empty string falls back to it. Safe before setup().
  void set_token_override(const std::string &token);
  bool has_token() const { return !this->runtime_token_.empty() || this->token_[0] != '\0'; }
#ifdef USE_TEXT_SENSOR
  /// Receives the outcome of every upload attempt ("HTTP 204", "connection failed", "no token").
  void set_status_sensor(text_sensor::TextSensor *sensor) { this->status_sensor_ = sensor; }
#endif
  void set_bucket(const char *bucket) { this->bucket_ = bucket; }
  void set_org(const char *org) { this->org_ = org; }
  void set_timestamp_unit(const char *unit) { this->timestamp_unit_ = unit; }
  void set_use_ssl(bool use_ssl) { this->use_ssl_ = use_ssl; }
  void set_send_mac(bool send_mac) { this->send_mac_ = send_mac; }
  void set_update_interval(uint32_t interval_ms) { this->update_interval_ = interval_ms; }
  void set_http_request(http_request::HttpRequestComponent *request) { this->http_request_ = request; }
  void set_time_source(time::RealTimeClock *time_source) { this->time_source_ = time_source; }

  /// Strings are literals generated by codegen and live in flash.
  void add_sensor(sensor::Sensor *sensor, const char *measurement, const char *field) {
    this->fields_.push_back({sensor, measurement, field, 0, false});
  }
  void add_tag(const char *key, const char *value) { this->tags_.push_back({key, value, nullptr}); }
  void add_tag(const char *key, std::function<std::string()> &&value) {
    this->tags_.push_back({key, nullptr, std::move(value)});
  }

 protected:
  struct Field {
    sensor::Sensor *sensor;
    const char *measurement;
    const char *field;
    uint8_t line;  ///< index into line_names_, assigned in setup()
    bool fresh;    ///< sensor produced a filtered value since it was last uploaded
  };
  struct Tag {
    const char *key;
    const char *value;                ///< static value, or nullptr when templated
    std::function<std::string()> fn;  ///< evaluated at each upload when value is nullptr
  };

  void publish_(const std::vector<sensor::Sensor *> *only);
  /// Fill body_ with one line per measurement; returns the number of fields written.
  size_t build_body_(const std::vector<sensor::Sensor *> *only);
  void append_tags_();
  void append_timestamp_();
  /// POST body_; on a transient failure schedule a retry, otherwise finish.
  void send_();
  void retry_or_drop_(const char *reason);
  /// Rebuild the Authorization header from whichever token is current.
  void update_auth_header_();
  void set_status_(const char *status);

  static void append_escaped_(std::string &out, const char *value);
  static void append_url_encoded_(std::string &out, const char *value);

  const char *host_{""};
  uint16_t port_{8086};
  const char *token_{""};
  std::string runtime_token_;
  const char *bucket_{""};
  const char *org_{""};
  const char *timestamp_unit_{"s"};
  int64_t timestamp_scale_{1};
  bool use_ssl_{true};
  bool send_mac_{true};
  uint32_t update_interval_{UPDATE_INTERVAL_NEVER};

  http_request::HttpRequestComponent *http_request_{nullptr};
  time::RealTimeClock *time_source_{nullptr};
#ifdef USE_TEXT_SENSOR
  text_sensor::TextSensor *status_sensor_{nullptr};
#endif

  std::vector<Field> fields_;
  std::vector<Tag> tags_;
  const char *line_names_[MAX_MEASUREMENTS]{};
  uint8_t line_count_{0};

  std::string url_;
  std::vector<http_request::Header> headers_;
  char mac_[MAC_ADDRESS_BUFFER_SIZE]{};

  std::string body_;  ///< payload buffer; capacity reserved in setup() and reused
  uint8_t attempt_{0};
  bool in_flight_{false};  ///< body_ holds a payload that is being sent or awaiting a retry
};

template<typename... Ts> class PublishAction : public Action<Ts...> {
 public:
  explicit PublishAction(InfluxDB *parent) : parent_(parent) {}

  void add_sensor(sensor::Sensor *sensor) { this->sensors_.push_back(sensor); }

  void play(const Ts &...x) override {
    if (this->sensors_.empty()) {
      this->parent_->publish();
    } else {
      this->parent_->publish(this->sensors_);
    }
  }

 protected:
  InfluxDB *parent_;
  std::vector<sensor::Sensor *> sensors_;
};

}  // namespace esphome::influxdb
