# SAMBA v2 FIRMWARE
# base configuration file for SAMBA using ESPHome
# written by Thomas Parkinson, April 2024


# Define substitutions for SAMBA device
substitutions:
  project_version: "1.99.33"
  local_timezone: "Australia/Sydney"
  tag_building: "create"
  tag_zone: "bears"
  calibration_co2_m: '1'
  calibration_co2_b: '0'
  calibration_lux_m: '1'
  calibration_lux_b: '0'
  calibration_ta_m: '1'
  calibration_ta_b: '0'
  calibration_rh_m: '1'
  calibration_rh_b: '0'
  calibration_tg_m: '1'
  calibration_tg_b: '0'
  calibration_as1_x: '0.00000000000162713705587024'
  calibration_as1_n: '17.7238215290214'
  calibration_as2_x: '0.110619801169189'
  calibration_as2_n: '3.93850903242043'

# Use packages to modularise codebase
packages:
  - !include config/esp32.yaml
  - !include config/wifi.yaml
  - !include config/ota.yaml
  - !include config/adc.yaml
  - !include config/led.yaml
  - !include config/rtc.yaml
  - !include config/homeassistant.yaml
  - !include config/sample.yaml
  - !include config/influx.yaml
  - !include config/co2.yaml
  - !include config/pm25.yaml
  - !include config/tvoc.yaml
  - !include config/illuminance.yaml
  - !include config/spl.yaml
  - !include config/tair.yaml
  - !include config/tglobe.yaml
  - !include config/airspeed.yaml
  - !include config/diagnostics.yaml

# Load custom components
external_components:
  - source: 
      type: local
      path: components
