# SAMBA v2 FIRMWARE
# base configuration file for SAMBA using ESPHome
# written by Thomas Parkinson, June 2025

# Define ESPHome settings
# https://esphome.io/components/esphome
esphome:
  name: "samba"
  friendly_name: "SAMBA"
  comment: "Low-cost monitoring of indoor environments - developed by the IEQ Lab"
  name_add_mac_suffix: true
  min_version: "2026.8.1"
  project:
    name: "IEQLab.SAMBA"
    version: "1.99.99"

# Set logging levels
# https://esphome.io/components/logger
logger:
  level: INFO
  logs:
    ads1115.sensor: ERROR
    component: NONE
    esp-idf: INFO
    http_request: ERROR
    i2c: INFO
    i2c_recovery: INFO
    influxdb: INFO
    light: NONE
    main: WARN
    ntc: NONE
    opt3001.sensor: NONE
    pmsx003: NONE
    resistance: NONE
    samba: INFO
    sd_spi_card: INFO
    senseair_i2c: ERROR
    sensirion_i2c: ERROR
    sgp4x: ERROR
    sensor: NONE
    sound_level_meter: ERROR
    sntp: INFO
    wire.cpp: NONE

# Import configuration files
# https://esphome.io/components/packages/
packages:
  - !include config/adc.yaml
  - !include config/airspeed.yaml
  - !include config/calibration.yaml
  - !include config/co2.yaml
  - !include config/diagnostics.yaml
  - !include config/esp32.yaml
  - !include config/globals.yaml
  - !include config/homeassistant.yaml
  - !include config/illuminance.yaml
  - !include config/influx.yaml
  - !include config/led.yaml
  - !include config/ota.yaml
  - !include config/pm25.yaml
  - !include config/rtc.yaml
  - !include config/sample.yaml
  - !include config/sd.yaml
  - !include config/spl.yaml
  - !include config/substitutions.yaml
  - !include config/tags.yaml
  - !include config/tair.yaml
  - !include config/tglobe.yaml
  - !include config/tvoc.yaml
  - !include config/wifi.yaml

# Import external components
# https://esphome.io/components/external_components/
external_components:
  - source: 
      type: local
      path: components

