# SAMBA v2 FIRMWARE
# base configuration file for SAMBA using ESPHome
# written by Thomas Parkinson, April 2024


# Define substitutions for SAMBA device
substitutions:
  project_version: "1.99.32"
  local_timezone: "Australia/Sydney"
  calibration_co2_m: '1'
  calibration_co2_b: '0'
  calibration_lux_m: '1'
  calibration_lux_b: '0'
  calibration_ta_m: '1'
  calibration_ta_b: '0'
  calibration_rh_m: '1'
  calibration_rh_b: '0'
  calibration_tg_m: '1'
  calibration_tg_b: '0'
  calibration_as1_x: '0.00000000000162713705587024'
  calibration_as1_n: '17.7238215290214'
  calibration_as2_x: '0.110619801169189'
  calibration_as2_n: '3.93850903242043'

# Use packages to modularise codebase
packages:
  device_base: !include esphome/base/esp32.yaml
  device_wifi: !include esphome/base/wifi.yaml
  device_ota: !include esphome/base/ota.yaml
  device_adc: !include esphome/base/adc.yaml
  device_led: !include esphome/base/led.yaml
  device_rtc: !include esphome/base/rtc.yaml
  device_ha: !include esphome/base/homeassistant.yaml
  measure_loop: !include esphome/measure/loop.yaml
  #measure_influx: !include esphome/measure/influx.yaml
  sensor_iaq: !include esphome/sensors/iaq.yaml
  sensor_light: !include esphome/sensors/light.yaml
  sensor_sound: !include esphome/sensors/sound.yaml
  sensor_thermal: !include esphome/sensors/thermal.yaml
  sensor_diagnostics: !include esphome/sensors/diagnostic.yaml

# load external components
external_components:
  - source: esphome/components
