# SAMBA v2 FIRMWARE
# base configuration file for SAMBA using ESPHome
# written by Thomas Parkinson, April 2024


# Define substitutions for device
substitutions:
  device_name: "samba"
  friendly_name: "SAMBA IEQ Monitor"
  project_version: "1.99.0"
  device_description: "Monitor indoor environmental quality using low-cost sensors - developed by the IEQ Lab"

# Use packages to modularise codebase
packages:
  device_base: !include esphome/base/esp32.yaml
  device_wifi: !include esphome/base/wifi.yaml
  home_assistant: !include esphome/base/homeassistant.yaml
  device_ota: !include esphome/base/ota.yaml
  periph_adc: !include esphome/peripherals/adc.yaml
  periph_led: !include esphome/peripherals/led.yaml
  periph_rtc: !include esphome/peripherals/rtc.yaml
  #measure_influx: !include esphome/measure/influx.yaml
  measure_loop: !include esphome/measure/loop.yaml
  sensor_iaq: !include esphome/sensors/iaq.yaml
  sensor_light: !include esphome/sensors/light.yaml
  sensor_sound: !include esphome/sensors/sound.yaml
  sensor_thermal: !include esphome/sensors/thermal.yaml
  diagnostics: !include esphome/sensors/diagnostic.yaml
  # remote_package:
  #   url: https://IEQLab/samba@main
  #   files: [firmware/base/esp32.yaml, 
  #           firmware/base/wifi.yaml]
  #   refresh: 1d


# load external components
external_components:
  - source: components
  # - source: github://IEQLab/samba@main
  #  components: [ i2s,  influxdb, sound_level_meter ]
