# SAMBA v2 FIRMWARE
# initial firmware flashed to new SAMBAs to facilitate setup
# written by Thomas Parkinson, July 2025


# Define global variable placeholders
# https://esphome.io/components/globals.html
globals:

  ## INFLUX TAGS ##
  - id: building_tag
    type: std::string
    max_restore_data_length: 24
    restore_value: yes
    initial_value: '"building"'

  - id: level_tag
    type: std::string
    max_restore_data_length: 24
    restore_value: yes
    initial_value: '"level"'

  - id: zone_tag
    type: std::string
    max_restore_data_length: 24
    restore_value: yes
    initial_value: '"zone"'

  ## DATA UPLOADS ##
  - id: influx_enable
    type: bool
    restore_value: yes
    initial_value: 'true'

  - id: sd_enable
    type: bool
    restore_value: yes
    initial_value: 'true'

  ## FIRMWARE UPDATES ##
  - id: updates_enable
    type: bool
    restore_value: yes
    initial_value: 'true'

  ## CALIBRATION COEFFICIENTS ##

  # CO2 Calibration (y = mx + b)
  - id: calibration_co2_m
    type: double
    restore_value: yes
    initial_value: '1.015844'
  - id: calibration_co2_b
    type: double
    restore_value: yes
    initial_value: '20.139092'

  # Lux Calibration (y = mx + b)
  - id: calibration_lux_m
    type: double
    restore_value: yes
    initial_value: '5.988641'
  - id: calibration_lux_b
    type: double
    restore_value: yes
    initial_value: '0.0'

  # Ta Calibration (y = mx + b)
  - id: calibration_ta_m
    type: double
    restore_value: yes
    initial_value: '0.9750601'
  - id: calibration_ta_b
    type: double
    restore_value: yes
    initial_value: '-3.9853163'

  # RH Calibration (y = mx + b)
  - id: calibration_rh_m
    type: double
    restore_value: yes
    initial_value: '0.8839748'
  - id: calibration_rh_b
    type: double
    restore_value: yes
    initial_value: '15.0758039'

  # Tg Calibration (y = mx + b)
  - id: calibration_tg_m
    type: double
    restore_value: yes
    initial_value: '0.9093902'
  - id: calibration_tg_b
    type: double
    restore_value: yes
    initial_value: '0.6127004'

  # Air speed 1 Calibration
  - id: calibration_as1_a
    type: double
    restore_value: yes
    initial_value: '0.000878414013334'
  - id: calibration_as1_b
    type: double
    restore_value: yes
    initial_value: '1.446429921572743'
  - id: calibration_as1_c
    type: double
    restore_value: yes
    initial_value: '1.344253500261520'

  # Air speed 2 Calibration
  - id: calibration_as2_a
    type: double
    restore_value: yes
    initial_value: '0.000700721710849'
  - id: calibration_as2_b
    type: double
    restore_value: yes
    initial_value: '1.592948717475052'
  - id: calibration_as2_c
    type: double
    restore_value: yes
    initial_value: '1.389994766781412'

# Make sure they get written to flash
# https://esphome.io/components/esphome.html#preferences-component
preferences:
  flash_write_interval: 5s

# Define ESPHome settings
esphome:
  name: "samba"
  friendly_name: "SAMBA Configuration"
  name_add_mac_suffix: true
  min_version: "2025.10.0"
  on_boot:
    - priority: 700
      then: 
        - light.turn_on:
            id: samba_led
            effect: strobe_rgb

# Define ESP32 board
esp32:
  board: esp32dev
  flash_size: 16MB
  framework:
    type: esp-idf

# Define logger
logger:
  level: DEBUG
  logs:
    esp32.preferences: DEBUG
    text: WARN
    number: WARN

# Define i2c
i2c:
  - id: bus_a
    scl: GPIO25
    sda: GPIO26
    scan: true
    frequency: 100kHz

# Configure UART
uart:
  - id: uart_pm
    rx_pin: GPIO16
    tx_pin: GPIO17
    baud_rate: 9600

# Define status LED component
light:
  - platform: esp32_rmt_led_strip
    id: samba_led
    rgb_order: GRB
    pin: GPIO27
    num_leds: 1
    rmt_symbols: 64
    use_psram: false
    chipset: ws2812
    effects:
      - strobe:
          name: "strobe_rgb"
          colors:
            - state: true
              brightness: 20%
              red: 0%
              green: 0%
              blue: 100%
              duration: 330ms
            - state: true
              brightness: 20%
              red: 0%
              green: 100%
              blue: 0%
              duration: 330ms
            - state: true
              brightness: 20%
              red: 100%
              green: 0%
              blue: 0%
              duration: 330ms
      - strobe:
          name: "pulse_blue"
          colors:
            - state: true
              brightness: 20%
              red: 0%
              green: 0%
              blue: 100%
              duration: 2000ms
              transition_length: 1500ms
            - state: false
              duration: 600ms
              transition_length: 500ms



## NETWORK ##

# Use captive portal for wifi configuration
captive_portal:

# Configure access point
wifi:
  ap:
    ssid: "samba_connect"
    ap_timeout: 30s
  on_connect:
    - light.turn_on:
        id: samba_led
        effect: pulse_blue

# Use web server to configure device
web_server:
  port: 80
  version: 3
  log: true
  sorting_groups:
    - id: sort_tags_settings
      name: "Influx Tags"
      sorting_weight: 10
    - id: sort_device_settings
      name: "Device Configuration"
      sorting_weight: 20
    - id: sort_calibration_settings
      name: "Calibration Coefficients"
      sorting_weight: 30
    - id: sort_firmware_settings
      name: "Firmware"
      sorting_weight: 40

# Report mac address
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP address"
      id: wifi_ip_address
      web_server:
        sorting_group_id: sort_device_settings
      icon: mdi:ip-network
    mac_address:
      name: "MAC address"
      id: wifi_mac_address
      web_server:
        sorting_group_id: sort_device_settings
      icon: mdi:network-pos


## UPDATES ##

# Configure over-the-air updates
ota:
  - platform: esphome
  - platform: web_server
  - platform: http_request
    on_progress:
      then:
        - logger.log:
            format: "OTA progress: %0.1f%%"
            args: ["x"]
            level: INFO
            tag: "samba"

# Enable HTTP Request component required for remote OTA
http_request:
    id: http_client
    verify_ssl: false

# Define firmware update buttons
button:

  # production firmware
  - platform: template
    name: "Flash production firmware"
    id: button_firmware
    web_server:
      sorting_group_id: sort_firmware_settings
    icon: mdi:check-all
    on_press:
      - logger.log:
          format: "Flashing SAMBA production firmware"
          level: INFO
          tag: "samba"
      - ota.http_request.flash:
          url: https://raw.githubusercontent.com/IEQLab/samba/main/firmware/samba_v1.99.92.bin
          md5: "fdadb4a9435505504aa36959e89eea62"

  # testing firmware
  - platform: template
    name: "Flash test firmware"
    id: button_custom
    web_server:
      sorting_group_id: sort_firmware_settings
    icon: mdi:bug-check
    on_press:
      - logger.log:
          format: "Flashing SAMBA testing firmware"
          level: INFO
          tag: "samba"
      - ota.http_request.flash:
          url: https://raw.githubusercontent.com/IEQLab/samba/main/firmware/samba_testing.bin
          md5_url: https://raw.githubusercontent.com/IEQLab/samba/main/firmware/samba_testing.md5


## INPUTS: INFLUX ##

# Define Influx tag fields
text:
  - platform: template
    name: "Building identifier"
    id: building_tag_input
    web_server:
      sorting_group_id: sort_tags_settings
    mode: text
    min_length: 1
    max_length: 24
    restore_value: true
    optimistic: true
    icon: mdi:office-building
    on_value:
      then:
        - lambda: |-
            id(building_tag) = x;

  - platform: template
    name: "Building level"
    id: level_tag_input
    web_server:
      sorting_group_id: sort_tags_settings
    mode: text
    min_length: 1
    max_length: 24
    restore_value: true
    optimistic: true
    icon: mdi:elevator-passenger-outline
    on_value:
      then:
        - lambda: |-
            id(level_tag) = x;

  - platform: template
    name: "Building zone"
    id: zone_tag_input
    web_server:
      sorting_group_id: sort_tags_settings
    mode: text
    min_length: 1
    max_length: 24
    restore_value: true
    optimistic: true
    icon: mdi:floor-plan
    on_value:
      then:
        - lambda: |-
            id(zone_tag) = x;


## INPUTS: COEFFICIENTS ##

# Define calibration fields
number:
  - platform: template
    name: "CO2 slope [m]"
    id: co2_m_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0
    max_value: 2
    step: 0.000001
    icon: mdi:molecule-co2
    lambda: |-
      return id(calibration_co2_m);
    set_action:
      - lambda: |-
          id(calibration_co2_m) = x;

  - platform: template
    name: "CO2 offset [b]"
    id: co2_b_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: -100
    max_value: 100
    step: 0.01
    icon: mdi:molecule-co2
    lambda: |-
      return id(calibration_co2_b);
    set_action:
      - lambda: |-
          id(calibration_co2_b) = x;

  - platform: template
    name: "Illuminance slope [m]"
    id: lux_m_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0
    max_value: 10
    step: 0.000001
    icon: mdi:sun-wireless-outline
    lambda: |-
      return id(calibration_lux_m);
    set_action:
      - lambda: |-
          id(calibration_lux_m) = x;

  - platform: template
    name: "Illuminance offset [b]"
    id: lux_b_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: -300
    max_value: 300
    step: 0.01
    icon: mdi:sun-wireless-outline
    lambda: |-
      return id(calibration_lux_b);
    set_action:
      - lambda: |-
          id(calibration_lux_b) = x;

  - platform: template
    name: "Air temperature slope [m]"
    id: ta_m_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0
    max_value: 5
    step: 0.0001
    icon: mdi:thermometer
    lambda: |-
      return id(calibration_ta_m);
    set_action:
      - lambda: |-
          id(calibration_ta_m) = x;

  - platform: template
    name: "Air temperature offset [b]"
    id: ta_b_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: -50
    max_value: 50
    step: 0.01
    icon: mdi:thermometer
    lambda: |-
      return id(calibration_ta_b);
    set_action:
      - lambda: |-
          id(calibration_ta_b) = x;

  - platform: template
    name: "Relative humidity slope [m]"
    id: rh_m_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0
    max_value: 2
    step: 0.001
    icon: mdi:water-percent
    lambda: |-
      return id(calibration_rh_m);
    set_action:
      - lambda: |-
          id(calibration_rh_m) = x;

  - platform: template
    name: "Relative humidity offset [b]"
    id: rh_b_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: -50
    max_value: 100
    step: 0.01
    icon: mdi:water-percent
    lambda: |-
      return id(calibration_rh_b);
    set_action:
      - lambda: |-
          id(calibration_rh_b) = x;

  - platform: template
    name: "Globe temperature slope [m]"
    id: tg_m_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0
    max_value: 2
    step: 0.001
    icon: mdi:thermometer
    lambda: |-
      return id(calibration_tg_m);
    set_action:
      - lambda: |-
          id(calibration_tg_m) = x;

  - platform: template
    name: "Globe temperature offset [b]"
    id: tg_b_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: -10
    max_value: 10
    step: 0.01
    icon: mdi:thermometer
    lambda: |-
      return id(calibration_tg_b);
    set_action:
      - lambda: |-
          id(calibration_tg_b) = x;

  - platform: template
    name: "Air speed 1 [a]"
    id: as1_a_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0.0
    max_value: 1.0
    step: 0.000000000000001
    icon: mdi:weather-windy
    lambda: |-
      return id(calibration_as1_a);
    set_action:
      - lambda: |-
          id(calibration_as1_a) = x;

  - platform: template
    name: "Air speed 1 [b]"
    id: as1_b_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0.0
    max_value: 3.0
    step: 0.000000000000001
    icon: mdi:weather-windy
    lambda: |-
      return id(calibration_as1_b);
    set_action:
      - lambda: |-
          id(calibration_as1_b) = x;

  - platform: template
    name: "Air speed 1 [c]"
    id: as1_c_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0.0
    max_value: 3.0
    step: 0.000000000000001
    icon: mdi:weather-windy
    lambda: |-
      return id(calibration_as1_c);
    set_action:
      - lambda: |-
          id(calibration_as1_c) = x;

  - platform: template
    name: "Air speed 2 [a]"
    id: as2_a_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0.0
    max_value: 1.0
    step: 0.000001
    icon: mdi:weather-windy
    lambda: |-
      return id(calibration_as2_a);
    set_action:
      - lambda: |-
          id(calibration_as2_a) = x;

  - platform: template
    name: "Air speed 2 [b]"
    id: as2_b_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0.0
    max_value: 5.0
    step: 0.0001
    icon: mdi:weather-windy
    lambda: |-
      return id(calibration_as2_b);
    set_action:
      - lambda: |-
          id(calibration_as2_b) = x;

  - platform: template
    name: "Air speed 2 [c]"
    id: as2_c_input
    web_server:
      sorting_group_id: sort_calibration_settings
    mode: box
    min_value: 0.0
    max_value: 5.0
    step: 0.000001
    icon: mdi:weather-windy
    lambda: |-
      return id(calibration_as2_c);
    set_action:
      - lambda: |-
          id(calibration_as2_c) = x;


## INPUTS: SETTINGS ##

# Define setting toggles
switch:
  - platform: template
    name: "InfluxDB uploads"
    id: switch_influx
    web_server:
      sorting_group_id: sort_device_settings
    restore_mode: DISABLED
    icon: mdi:cloud-upload-outline
    lambda: |-
      return id(influx_enable);
    turn_on_action:
      - lambda: |-
          id(influx_enable) = true;
    turn_off_action:
      - lambda: |-
          id(influx_enable) = false;

  - platform: template
    name: "SD card logging"
    id: switch_sd
    web_server:
      sorting_group_id: sort_device_settings
    restore_mode: DISABLED
    icon: mdi:sd
    lambda: |-
      return id(sd_enable);
    turn_on_action:
      - lambda: |-
          id(sd_enable) = true;
    turn_off_action:
      - lambda: |-
          id(sd_enable) = false;

  - platform: template
    name: "Automatic updates"
    id: switch_updates
    web_server:
      sorting_group_id: sort_device_settings
    restore_mode: DISABLED
    icon: mdi:update
    lambda: |-
      return id(updates_enable);
    turn_on_action:
      - lambda: |-
          id(updates_enable) = true;
    turn_off_action:
      - lambda: |-
          id(updates_enable) = false;

