# SAMBA v2 FIRMWARE
# base configuration file for SAMBA using ESPHome
# written by Thomas Parkinson, April 2024


# Define substitutions for device
substitutions:
  device_name: "samba"
  friendly_name: "SAMBA IEQ Monitor"
  project_version: "1.99.0"
  device_description: "Monitor indoor environmental quality using low-cost sensors - developed by the IEQ Lab"

# Use packages to modularise codebase
packages:
  device_base: !include firmware/base/esp32.yaml
  device_wifi: !include firmware/base/wifi.yaml
  home_assistant: !include firmware/base/homeassistant.yaml
  device_ota: !include firmware/base/ota.yaml
  component_adc: !include firmware/components/adc.yaml
  component_led: !include firmware/components/led.yaml
  component_rtc: !include firmware/components/rtc.yaml
  #measure_influx: !include firmware/measure/influx.yaml
  measure_loop: !include firmware/measure/loop.yaml
  sensor_iaq: !include firmware/sensors/iaq.yaml
  sensor_light: !include firmware/sensors/light.yaml
  sensor_sound: !include firmware/sensors/sound.yaml
  sensor_thermal: !include firmware/sensors/thermal.yaml
  diagnostics: !include firmware/sensors/diagnostic.yaml

# load external components
external_components:
  - source: firmware/external_components
