# SAMBA v2 FIRMWARE
# base configuration file for SAMBA using ESPHome
# written by Thomas Parkinson, April 2024


# Define substitutions for device
substitutions:
  device_name: "samba"
  friendly_name: "SAMBA IEQ Monitor"
  project_version: "1.99.32"
  device_description: "Monitor indoor environmental quality using low-cost sensors - developed by the IEQ Lab"

# Use packages to modularise codebase
packages:
  device_base: !include esphome/base/esp32.yaml
  device_wifi: !include esphome/base/wifi.yaml
  device_ota: !include esphome/base/ota.yaml
  device_adc: !include esphome/base/adc.yaml
  device_led: !include esphome/base/led.yaml
  device_rtc: !include esphome/base/rtc.yaml
  device_ha: !include esphome/base/homeassistant.yaml
  measure_loop: !include esphome/measure/loop.yaml
  #measure_influx: !include esphome/measure/influx.yaml
  sensor_iaq: !include esphome/sensors/iaq.yaml
  sensor_light: !include esphome/sensors/light.yaml
  sensor_sound: !include esphome/sensors/sound.yaml
  sensor_thermal: !include esphome/sensors/thermal.yaml
  sensor_diagnostics: !include esphome/sensors/diagnostic.yaml

# load external components
external_components:
  - source: esphome/components
