# SAMBA v2 FIRMWARE
# initial firmware flashed to new SAMBAs to facilitate setup
# written by Thomas Parkinson, July 2025


# Define calibration coefficients for SAMBA
# https://esphome.io/components/substitutions.html
substitutions:
  building_name: "building"
  zone_name: "zone"
  co2_m: "1.015844"
  co2_b: "20.139092"
  lux_m: "6.227522"
  lux_b: "-31.631162"
  ta_m: "0.9750601"
  ta_b: "-3.9853163"
  rh_m: "0.8839748"
  rh_b: "15.0758039"
  tg_m: "0.9093902"
  tg_b: "0.6127004"  
  as1_a: "1.00000000000162713705587024"
  as1_b: "17.7238215290214"
  as2_a: "0.110619801169189"
  as2_b: "3.93850903242043"

# Define global variable placeholders
# https://esphome.io/components/globals.html
globals:
  - id: building_tag
    type: std::string
    max_restore_data_length: 24
    restore_value: yes
    initial_value: '"x"'
  - id: zone_tag
    type: std::string
    max_restore_data_length: 24
    restore_value: yes
    initial_value: '"x"'
  - id: calibration_co2
    type: double[2]
    restore_value: yes
    initial_value: '{1.0, 1.0}'
  - id: calibration_lux
    type: double[2]
    restore_value: yes
    initial_value: '{1.0, 1.0}'
  - id: calibration_ta
    type: double[2]
    restore_value: yes
    initial_value: '{1.0, 1.0}'
  - id: calibration_rh
    type: double[2]
    restore_value: yes
    initial_value: '{1.0, 1.0}'
  - id: calibration_tg
    type: double[2]
    restore_value: yes
    initial_value: '{1.0, 1.0}'
  - id: calibration_as1
    type: double[2]
    restore_value: yes
    initial_value: '{1.0, 1.0}'
  - id: calibration_as2
    type: double[2]
    restore_value: yes
    initial_value: '{1.0, 1.0}'

# Make sure they get written to flash
# https://esphome.io/components/esphome.html#preferences-component
preferences:
  flash_write_interval: 1s

# Define ESPHome settings
# https://esphome.io/components/esphome
esphome:
  name: "samba"
  name_add_mac_suffix: true
  min_version: "2025.6.1"
  on_boot:
    - priority: 100
      then: 
        - light.turn_on:
            id: samba_led
            effect: pulse_fast

# Define ESP32 board
# https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32e_esp32-wroom-32ue_datasheet_en.pdf
esp32:
  board: esp32dev
  flash_size: 16MB
  framework:
    type: arduino

# Define logger
# https://esphome.io/components/logger
logger:
  level: DEBUG

# Use captive portal for wifi configuration
# https://esphome.io/components/captive_portal.html
captive_portal:

# Configure access point
# https://esphome.io/components/wifi
wifi:
  ap:
    ssid: "samba_connect"
    ap_timeout: 30s

# Write globals to flash once connected to WiFi
  on_connect:
    - lambda: |-
        id(zone_tag) = "${zone_name}";
        id(building_tag) = "${building_name}";
        id(calibration_co2)[0] = double(${co2_m});
        id(calibration_co2)[1] = double(${co2_b});
        id(calibration_lux)[0] = double(${lux_m});
        id(calibration_lux)[1] = double(${lux_b});
        id(calibration_ta)[0] = double(${ta_m});
        id(calibration_ta)[1] = double(${ta_b});
        id(calibration_rh)[0] = double(${rh_m});
        id(calibration_rh)[1] = double(${rh_b});
        id(calibration_tg)[0] = double(${tg_m});
        id(calibration_tg)[1] = double(${tg_b});
        id(calibration_as1)[0] = double(${as1_a});
        id(calibration_as1)[1] = double(${as1_b});
        id(calibration_as2)[0] = double(${as2_a});
        id(calibration_as2)[1] = double(${as2_b});
            
# Print out globals
    - delay: 1s
    - logger.log: 
        format: "SAMBA %s is born"
        args: ['WiFi.macAddress().c_str()']
        level: INFO
        tag: "samba"
    - logger.log: 
        format: "IP address is %s"
        args: ['WiFi.localIP().toString().c_str()']
        level: INFO
        tag: "samba"
    - logger.log:
        format: "SAMBA assigned to zone: %s in building: %s"
        args: [ 'id(zone_tag).c_str()', 'id(building_tag).c_str()' ]
        level: INFO
        tag: "samba"
    - logger.log:
        format: "CO2 calibration: y = %.12fx + %.12fb"
        args: [ 'id(calibration_co2)[0]', 'id(calibration_co2)[1]' ]
        level: INFO
        tag: "samba"
    - logger.log:
        format: "Lux calibration: y = %.12fx + %.12fb"
        args: [ 'id(calibration_lux)[0]', 'id(calibration_lux)[1]' ]
        level: INFO
        tag: "samba"
    - logger.log:
        format: "Ta calibration: y = %.12fx + %.12fb"
        args: [ 'id(calibration_ta)[0]', 'id(calibration_ta)[1]' ]
        level: INFO
        tag: "samba"
    - logger.log:
        format: "RH calibration: y = %.12fx + %.12fb"
        args: [ 'id(calibration_rh)[0]', 'id(calibration_rh)[1]' ]
        level: INFO
        tag: "samba"
    - logger.log:
        format: "Tg calibration: y = %.12fx + %.12fb"
        args: [ 'id(calibration_tg)[0]', 'id(calibration_tg)[1]' ]
        level: INFO
        tag: "samba"
    - logger.log:
        format: "Air speed 1 calibration: y = %.16f * x^%.12f"
        args: [ 'id(calibration_as1)[0]', 'id(calibration_as1)[1]' ]
        level: INFO
        tag: "samba"
    - logger.log:
        format: "Air speed 2 calibration: y = %.16f * x^%.12f"
        args: [ 'id(calibration_as2)[0]', 'id(calibration_as2)[1]' ]
        level: INFO
        tag: "samba"

# Check for SAMBA firmware online
    - delay: 10s
    - logger.log:
        format: "Checking for SAMBA firmware"
        level: INFO
        tag: "samba"
    - ota.http_request.flash:
        md5_url: https://github.com/IEQLab/samba/raw/main/firmware/firmware.md5
        url: https://github.com/IEQLab/samba/raw/main/firmware/firmware.ota.bin

# Enable HTTP Request component required for remote OTA
# https://esphome.io/components/http_request.html
http_request:
    id: http_client
    verify_ssl: false

# Configure over-the-air updates
# https://esphome.io/components/ota/
# https://esphome.io/components/ota/http_request
ota:
  - platform: esphome
    password: !secret ota_password
  - platform: http_request
    on_progress:
      then:
        - logger.log:
            format: "OTA progress: %0.1f%%"
            args: ["x"]
            level: INFO
            tag: "samba"

# Define status LED component
# https://esphome.io/components/light/esp32_rmt_led_strip.html
light:
  - platform: esp32_rmt_led_strip
    id: samba_led
    rgb_order: GRB
    pin: GPIO27
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    effects:
      - pulse:
          name: "pulse_fast"
          transition_length: 0.5s
          update_interval: 0.5s
          max_brightness: 0.20
