# SAMBA v2 FIRMWARE
# configure ADC component of SAMBA
# written by Thomas Parkinson, May 2024


# Define ADC component
# https://esphome.io/components/sensor/ads1115.html
ads1115:
  - address: 0x4B
    continuous_mode: off
    id: ads_dac

# Define raw measurements for sensors
sensor:
# Air speed sensor 1
  - platform: ads1115
    ads1115_id: ads_dac
    id: ads_as1
    multiplexer: 'A0_GND'
    gain: 6.144
    update_interval: 1s
    internal: true

# Air speed sensor 2
  - platform: ads1115
    ads1115_id: ads_dac
    id: ads_as2
    multiplexer: 'A1_GND'
    gain: 6.144
    update_interval: 1s
    internal: true

# NTC thermistor
  - platform: ads1115
    ads1115_id: ads_dac
    id: ads_ntc
    multiplexer: 'A2_GND'
    gain: 6.144
    update_interval: 30s
    internal: true