# SAMBA v2 FIRMWARE
# configure ESP device for SAMBA
# written by Thomas Parkinson, May 2024


# Define ESPHome settings
# https://esphome.io/components/esphome
esphome:
  name: '${device_name}'
  comment: '${device_description}'
  name_add_mac_suffix: true
  project:
    name: "IEQLab.SAMBA"
    version: "${project_version}"
  on_boot:
    - priority: 600
      then:
        - ds1307.read_time:
    - priority: -100
      then: 
        - logger.log: 
            level: INFO
            format: "A SAMBA is born :-)"
        - component.update: sys_uptime
        - component.update: sys_ip
        - logger.log: 
            level: INFO
            format: "IP address is %s"
            args: ['id(sys_ip).state.c_str()']

# Define ESP32 board
# https://www.adafruit.com/product/5400
esp32:
  board: adafruit_feather_esp32_v2 #esp32dev

# Set logging to errors only
# https://esphome.io/components/logger
logger:
  level: INFO
  logs:
    main: INFO
    component: ERROR

# Define i2c pins
# https://esphome.io/components/i2c
i2c:
  - id: bus_a
    sda: 22
    scl: 20
    scan: true

# Configure UART
# https://esphome.io/components/uart
uart:
  - id: uart_pm
    rx_pin: 7
    tx_pin: 8
    baud_rate: 9600
  - id: uart_co2
    rx_pin: 27
    tx_pin: 15
    baud_rate: 9600
    stop_bits: 1
    parity: none

# Configure modbus controller for K30 CO2 sensor
# https://esphome.io/components/modbus_controller.html
modbus:
  send_wait_time: 200ms
  uart_id: uart_co2
  id: bus_co2

modbus_controller:
  - id: modbus_co2
    address: 0xFE
    modbus_id: bus_co2
    command_throttle: 500ms
    setup_priority: -10
    update_interval: 30s

# Configure i2s
# https://github.com/stas-sl/esphome-sound-level-meter
i2s:
  bck_pin: 32
  ws_pin: 25
  din_pin: 33
  sample_rate: 48000
  bits_per_sample: 32
  dma_buf_count: 8
  dma_buf_len: 256
  use_apll: true  # default: false
  channel: right
  bits_shift: 8   # default: 0
