# SAMBA v2 FIRMWARE
# configure ESP device for SAMBA
# written by Thomas Parkinson, May 2024


# Define ESPHome settings
# https://esphome.io/components/esphome
esphome:
  name: '${device_name}'
  comment: '${device_description}'
  name_add_mac_suffix: true
  project:
    name: "IEQLab.SAMBA"
    version: "${project_version}"
  on_boot:
    - priority: 600
      then:
        - ds1307.read_time:
    - priority: -100
      then: 
        - light.turn_on:
            id: samba_led
            brightness: 0.25
        - logger.log: 
            format: "A SAMBA is born (%s) :-)"
            args: ['id(sys_mac).state.c_str()']
            level: INFO
            tag: "samba"
        - component.update: sys_uptime
        - component.update: sys_ip
        - logger.log: 
            format: "IP address is %s"
            args: ['id(sys_ip).state.c_str()']
            level: INFO
            tag: "samba"
        - delay: 1000ms
        - light.turn_off:
            id: samba_led

# Define ESP32 board
# https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32e_esp32-wroom-32ue_datasheet_en.pdf
esp32:
  board: esp32dev
  flash_size: 16MB
  framework:
    type: esp-idf

# Set logging to errors only
# https://esphome.io/components/logger
logger:
  level: INFO
  logs:
    main: INFO
    component: NONE
    sensor: INFO
    ads1115.sensor: INFO
    ntc: INFO
    opt3001.sensor: INFO
    pmsx003: INFO
    k30: INFO
    sgp4x: NONE
    sound_level_meter: INFO
    wire.cpp: NONE

# Define i2c pins
# https://esphome.io/components/i2c
i2c:
  - id: bus_a
    scl: GPIO25
    sda: GPIO26
    scan: true
    frequency: 50kHz

# Configure UART
# https://esphome.io/components/uart
uart:
  - id: uart_pm
    rx_pin: GPIO16
    tx_pin: GPIO17
    baud_rate: 9600

# Configure i2s
# https://github.com/stas-sl/esphome-sound-level-meter
i2s:
  bck_pin: GPIO13
  ws_pin: GPIO33
  din_pin: GPIO32
  sample_rate: 48000
  bits_per_sample: 32
  dma_buf_count: 8
  dma_buf_len: 256
  use_apll: true  # default: false
  channel: left
  bits_shift: 8   # default: 0
