# SAMBA v2 FIRMWARE
# configure SAMBA to use Home Assistant
# written by Thomas Parkinson, May 2024


# Enable Home Assistant API
# https://esphome.io/components/api.html
api:

# Add restart button to Home Assistant
# https://esphome.io/components/button/restart
button:
  - platform: restart
    name: "Restart SAMBA"
    icon: mdi:restart
    entity_category: "config"

# Add shutdown button to Home Assistant
# https://esphome.io/components/button/shutdown
  - platform: shutdown
    name: "Shutdown SAMBA"
    icon: mdi:power
    entity_category: "config"

# Add safe mode button to Home Assistant
  - platform: safe_mode
    name: "Restart SAMBA (Safe Mode)"
    icon: mdi:backup-restore
    entity_category: "config"
