# SAMBA v2 FIRMWARE
# configure LED component of SAMBA
# written by Thomas Parkinson, May 2024


# Define LED component
# https://esphome.io/components/light/esp32_rmt_led_strip.html
light:
  - platform: esp32_rmt_led_strip
    id: samba_led
    rgb_order: GRB
    pin: GPIO27
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812