# SAMBA v2 FIRMWARE
# configure OTA support for SAMBA using ESPHome
# written by Thomas Parkinson, May 2024


# Enable OTA access
# https://esphome.io/components/ota.html
ota:
  - platform: esphome
    password: !secret ota_password