# SAMBA v2 FIRMWARE
# configure SAMBA WiFi
# written by Thomas Parkinson, May 2024


# Configre wifi
# https://esphome.io/components/wifi.html
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
#  - ssid: !secret enterprise_ssid
#    eap:
#      username: !secret enterprise_user
#      password: !secret enterprise_password
#      ttls_phase_2: mschapv2
  power_save_mode: none
#  manual_ip: 
#    static_ip: 192.168.1.253
#    gateway: 192.168.1.1
#    subnet: 255.255.255.0

# Set up a wifi access point
#  ap:
#    ssid: '${friendly_name}'
#    password: !secret fallback_ssid_password

# Use captive portal to allow WiFi crediential input
# https://esphome.io/components/captive_portal.html
captive_portal:
