# SAMBA v2 FIRMWARE
# configure MEMS microphone and SPL meter on SAMBA
# written by Thomas Parkinson, May 2024


# load external component from Github (credit to Stas Slunkov)
external_components:
  - source: github://stas-sl/esphome-sound-level-meter

# define SPL sensor
# https://github.com/stas-sl/esphome-sound-level-meter/tree/main
sound_level_meter:
  id: sound_spl
  update_interval: 30s
  is_on: true
  buffer_size: 1024  # buffer_size in samples
  warmup_interval: 1000ms # ignore audio data at startup
  # audio processing task
  task_stack_size: 4096
  task_priority: 2
  task_core: 1
  # mic configuration
  mic_sensitivity: -26dB
  mic_sensitivity_ref: 94dB
  offset: 0dB

  # for flexibility sensors are organized hierarchically into groups
  groups:
    # group 1 (mic eq)
    - filters:
        - type: sos
          coeffs:
            # change to ICS-43434
            # https://invensense.tdk.com/products/ics-43434/
            # INMP441:
            #      b0            b1           b2          a1            a2
            - [ 1.0019784 , -1.9908513  , 0.9889158 , -1.9951786  , 0.99518436]

      groups:
        # group 1.1 (no weighting)
        - sensors:
            - type: eq
              id: spl_lzeq
              unit_of_measurement: dBZ
              internal: true

        # group 1.2 (A-weighting)
        - filters:
            - type: sos
              coeffs:
                # A-weighting:
                #       b0           b1            b2             a1            a2
                - [ 0.16999495 ,  0.741029   ,  0.52548885 , -0.11321865 , -0.056549273]
                - [ 1.         , -2.00027    ,  1.0002706  , -0.03433284 , -0.79215795 ]
                - [ 1.         , -0.709303   , -0.29071867 , -1.9822421  ,  0.9822986  ]
          
          sensors:
            - type: eq
              id: spl_laeq
              update_interval: 500ms
              internal: true
              filters:
                - median:
                    window_size: 600
                    send_every: 60
                    send_first_at: 60

        # group 1.3 (C-weighting)
        - filters:
            - type: sos
              coeffs:
                # C-weighting:
                #       b0             b1             b2             a1             a2
                - [-0.49651518  , -0.12296628  , -0.0076134163, -0.37165618   , 0.03453208  ]
                - [ 1.          ,  1.3294908   ,  0.44188643  ,  1.2312505    , 0.37899444  ]
                - [ 1.          , -2.          ,  1.          , -1.9946145    , 0.9946217   ]
          
          sensors:
            - type: eq
              id: spl_lceq
              unit_of_measurement: dBC
              internal: true


# SPL sensor
sensor:
  - platform: template
    id: sensor_spl
    name: "Sound Pressure Level"
    update_interval: never
    accuracy_decimals: 1
    unit_of_measurement: dBA
    device_class: sound_pressure
    icon: "mdi:volume-high"
    lambda: |-
      return id(spl_laeq).state;
