# SAMBA v2 FIRMWARE
# configure K30 carbon dioxide sensor on SAMBA
# custom component for K30 sensor
# written by Thomas Parkinson, May 2024


# Define sensor
sensor:
  - platform: senseair_i2c
    id: k30_co2
    i2c_id: bus_a
    address: 0x69
    internal: true
    update_interval: 15s
    abc_interval: 0s
    retry_delay_ms: 100
    max_retries: 5
    filters:
      - filter_out: nan
      - clamp:
          min_value: 380
          max_value: 9000
          ignore_out_of_range: true
      - median:
          window_size: 20
          send_every: 3
          send_first_at: 1

# Define CO2 measurements
  - platform: template
    id: samba_co2
    name: "Carbon Dioxide"
    update_interval: 180h
    accuracy_decimals: 0
    device_class: carbon_dioxide
    unit_of_measurement: "ppm"
    icon: mdi:molecule-co2
    filters:
      - lambda: |-
          return ((id(calibration_co2)[0] * id(k30_co2).state) + id(calibration_co2)[1]);
