# SAMBA v2 FIRMWARE
# configure ESP microcontroller
# written by Thomas Parkinson, May 2024


# Define ESP32 board
# https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32e_esp32-wroom-32ue_datasheet_en.pdf
esp32:
  variant: esp32
#  board: esp32dev
  flash_size: 16MB
  cpu_frequency: 240MHZ
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FATFS_LFN_NONE: "n"
      CONFIG_FATFS_LFN_HEAP: "y"
      CONFIG_FATFS_MAX_LFN: "255"
    advanced:
      include_builtin_idf_components: ["fatfs"]
      disable_vfs_support_termios: false
      disable_vfs_support_select: false
      disable_vfs_support_dir: false
      minimum_chip_revision: "3.1"

# Define initialisation code
# https://esphome.io/components/esphome/#on_boot
esphome:
  on_boot:
    - priority: 100
      then: 
        - light.turn_on:
            id: samba_led
            effect: strobe_g
        - component.update: sys_uptime
        - delay: 1000ms
    - priority: -100
      then:
      
        # Synchronise system to RTC clock
        - delay: 200ms
        - ds1307.read_time:
        


# Configure i2c bus
# https://esphome.io/components/i2c
i2c:
  - id: bus_a
    scl: GPIO25
    sda: GPIO26
    scan: false
    frequency: 50kHz
    timeout: 13ms

# Configure UART bus
# https://esphome.io/components/uart
uart:
  - id: uart_pm
    rx_pin: GPIO16
    tx_pin: GPIO17
    baud_rate: 9600
