# SAMBA v2 FIRMWARE
# configure over-the-air update support
# written by Thomas Parkinson, May 2024


# Define global variables that persist after reset
# https://esphome.io/components/globals.html
globals:
  - id: local_timezone
    type: std::string
    restore_value: yes
  - id: tag_building
    type: std::string
    restore_value: yes
  - id: tag_zone
    type: std::string
    restore_value: yes
  - id: calibration_co2
    type: double[2]
    restore_value: yes
  - id: calibration_lux
    type: double[2]
    restore_value: yes
  - id: calibration_ta
    type: double[2]
    restore_value: yes
  - id: calibration_rh
    type: double[2]
    restore_value: yes
  - id: calibration_tg
    type: double[2]
    restore_value: yes
  - id: calibration_as1
    type: double[2]
    restore_value: yes
  - id: calibration_as2
    type: double[2]
    restore_value: yes
