# SAMBA v2 FIRMWARE
# Create global parameters and restore from flash
# written by Thomas Parkinson, June 2025


# Define global variables that persist after reset
# https://esphome.io/components/globals.html
globals:
  - id: calibration_co2
    type: double[2]
    restore_value: no
  - id: calibration_lux
    type: double[2]
    restore_value: no
  - id: calibration_ta
    type: double[2]
    restore_value: no
  - id: calibration_rh
    type: double[2]
    restore_value: no
  - id: calibration_tg
    type: double[2]
    restore_value: no
  - id: calibration_as1
    type: double[2]
    restore_value: no
  - id: calibration_as2
    type: double[2]
    restore_value: no
