# SAMBA v2 FIRMWARE
# Create global parameters and restore from flash
# written by Thomas Parkinson, June 2025


# Define global variables that persist after reset
# https://esphome.io/components/globals.html
globals:
  - id: building_tag
    type: std::string
    max_restore_data_length: 24
    restore_value: yes
    initial_value: '"building"'

  - id: level_tag
    type: std::string
    max_restore_data_length: 24
    restore_value: yes
    initial_value: '"level"'

  - id: zone_tag
    type: std::string
    max_restore_data_length: 24
    restore_value: yes
    initial_value: '"zone"'

  - id: updates_enable
    type: bool
    restore_value: yes
    initial_value: 'true'

  - id: influx_enable
    type: bool
    restore_value: yes
    initial_value: 'true'

  - id: sd_enable
    type: bool
    restore_value: yes
    initial_value: 'true'

  # CO2 calibration (y = mx + b)
  - id: calibration_co2_m
    type: double
    restore_value: yes
    initial_value: '1.0'
  - id: calibration_co2_b
    type: double
    restore_value: yes
    initial_value: '20.0'

  # Illuminance calibration
  - id: calibration_lux_m
    type: double
    restore_value: yes
    initial_value: '7.5'
  - id: calibration_lux_b
    type: double
    restore_value: yes
    initial_value: '0.0'

  # Air temperature calibration
  - id: calibration_ta_m
    type: double
    restore_value: yes
    initial_value: '1.42'
  - id: calibration_ta_b
    type: double
    restore_value: yes
    initial_value: '-17.5'

  # RH calibration
  - id: calibration_rh_m
    type: double
    restore_value: yes
    initial_value: '0.70'
  - id: calibration_rh_b
    type: double
    restore_value: yes
    initial_value: '22.0'

  # Globe temperature calibration
  - id: calibration_tg_m
    type: double
    restore_value: yes
    initial_value: '1.37'
  - id: calibration_tg_b
    type: double
    restore_value: yes
    initial_value: '-12.5'

  # Air speed 1 calibration (power function)
  - id: calibration_as1_a
    type: double
    restore_value: yes
    initial_value: '1.208214'
  - id: calibration_as1_b
    type: double
    restore_value: yes
    initial_value: '1.299113'
  - id: calibration_as1_c
    type: double
    restore_value: yes
    initial_value: '-0.0003'
  - id: calibration_as1_d0
    type: double
    restore_value: yes
    initial_value: '2.857'
  - id: calibration_as1_d1
    type: double
    restore_value: yes
    initial_value: '-0.067'

  # Air speed 2 calibration
  - id: calibration_as2_a
    type: double
    restore_value: yes
    initial_value: '1.298747'
  - id: calibration_as2_b
    type: double
    restore_value: yes
    initial_value: '2.275216'
  - id: calibration_as2_c
    type: double
    restore_value: yes
    initial_value: '0.0018'
  - id: calibration_as2_d0
    type: double
    restore_value: yes
    initial_value: '2.515'
  - id: calibration_as2_d1
    type: double
    restore_value: yes
    initial_value: '-0.049'

# Define flash write interval
# https://esphome.io/components/esphome.html#preferences-component
preferences:
  flash_write_interval: 1min
