# SAMBA v2 FIRMWARE
# configure SAMBA to use Home Assistant API
# https://esphome.io/components/api.html
# written by Thomas Parkinson, May 2024


# Enable Home Assistant API
api:
  reboot_timeout: 0s

# Add restart button to Home Assistant
# https://esphome.io/components/button/restart
button:
  - platform: restart
    name: "Restart SAMBA"
    icon: mdi:restart
    entity_category: "config"

# Add shutdown button to Home Assistant
# https://esphome.io/components/button/shutdown
  - platform: shutdown
    name: "Shutdown SAMBA"
    icon: mdi:power
    entity_category: "config"

# Add safe mode button to Home Assistant
# https://esphome.io/components/safe_mode.html
  - platform: safe_mode
    name: "Restart SAMBA (Safe Mode)"
    icon: mdi:backup-restore
    entity_category: "config"

# Add factory reset switch to Home Assistant
# https://esphome.io/components/switch/factory_reset.html
switch:
  - platform: factory_reset
    name: "Factory Restore SAMBA"
    icon: mdi:alert
    entity_category: "config"

# Toggle Influx uploads
  - platform: template
    name: "InfluxDB Upload"
    icon: mdi:cloud-upload-outline
    entity_category: "config"
    restore_mode: DISABLED
    lambda: |-
      return id(influx_enable);
    turn_on_action:
      - lambda: 'id(influx_enable) = true;'
    turn_off_action:
      - lambda: 'id(influx_enable) = false;'
