# SAMBA v2 FIRMWARE
# configure OPT3001 light sensor
# written by Thomas Parkinson, May 2024


# Define sensor
# https://github.com/esphome/esphome/pull/6625
sensor:
  - platform: opt3001
    id: opt_lux
    update_interval: 20s
    internal: true
    address: 0x45
    filters:
      - clamp:
          min_value: 0
          max_value: 10000
          ignore_out_of_range: true
      - median:
          window_size: 6
          send_every: 6
          send_first_at: 6


# Define illuminance measurements
  - platform: template
    id: samba_lux
    name: "Illuminance"
    update_interval: never
    accuracy_decimals: 0
    device_class: illuminance
    unit_of_measurement: "lx"
    icon: mdi:sun-wireless-outline
    filters:
      - lambda: |-
          return ((id(calibration_lux)[0] * id(opt_lux).state) + id(calibration_lux)[1]);
      - clamp:
          min_value: 0
          max_value: 10000
          ignore_out_of_range: false
