# SAMBA v2 FIRMWARE
# configure upload of data to remote InfluxDB server
# custom component
# written by Thomas Parkinson, May 2024


# Define InfluxDB connection
influxdb:
  id: influx
  http_request_id: http_client
  time_id: sntp_time
  host: "${influx_host}"
  port: "${influx_port}"
  token: "${influx_token}"
  bucket: "${influx_bucket}"
  org: "${influx_org}"
  use_ssl: true
  send_mac: true
  timestamp_unit: "s"
  update_interval: never

  # Define Influx measurements for sensors
  sensor_names:
    air_temperature: "air_temp"
    relative_humidity: "rel_humidity"
    globe_temperature: "globe_temp"
    radiant_temperature: "rad_temp"
    air_speed: "air_speed"
    carbon_dioxide: "co2"
    pm2_5: "pm25"
    tvoc: "tvoc"
    nox_index: "nox"
    illuminance: "illuminance"
    laeq: "la_eq"
    lamin: "la_min"
    lamax: "la_max"
    wifi_signal: "wifi"
    device_uptime: "uptime"

#  # Define Influx field keys (defaults to 'value')
#  field_names:
#    air_temp: "celsius"

  # Define global tags applied to all measurements
  global_tags:
    building: "wilkinson"
    level: "420"
    zone: "testing"

#  # Define measurement-specific tags
#  sensor_tags:
#    air_temperature:
#      sensor_type: "sht4x"

# Toggle Influx uploads
switch:
  - platform: template
    name: "InfluxDB Upload"
    id: switch_influx
    icon: mdi:cloud-upload-outline
    entity_category: "config"
    restore_mode: DISABLED
    lambda: |-
      return id(influx_enable);
    turn_on_action:
      - lambda: 'id(influx_enable) = true;'
    turn_off_action:
      - lambda: 'id(influx_enable) = false;'
