# SAMBA v2 FIRMWARE
# configure upload of data to remote InfluxDB server
# custom component
# written by Thomas Parkinson, May 2024


# Define InfluxDB connection
influxdb_writer:
  id: influx_writer
  use_ssl: true
  host: "${influx_host}"
  port: "${influx_port}"
  token: "${influx_token}"
  org: "${influx_org}"
  bucket: "${influx_bucket}"
  timestamp_unit: "s"
  http_request_id: http_client
  time_id: sntp_time
  send_mac: true

  # Define Influx measurements for sensors
  sensor_names:
    samba_temperature: "Air Temperature"
    samba_humidity: "Relative Humidity"
    samba_globe: "Globe Temperature"
    samba_airspeed: "Air Speed"
    samba_co2: "Carbon Dioxide"
    samba_pm25: "PM2.5"
    samba_voc: "TVOC"
    samba_nox: "NOx Index"
    samba_lux: "Illuminance"
    samba_spl: "Sound Pressure Level"

  # Define Influx tags for fields
  sensor_tags:
    samba_temperature:
      building: "building"
      zone: "zone"
    samba_humidity:
      building: "building"
      zone: "zone"
    samba_globe:
      building: "building"
      zone: "zone"
    samba_airspeed:
      building: "building"
      zone: "zone"
    samba_co2:
      building: "building"
      zone: "zone"
    samba_pm25:
      building: "building"
      zone: "zone"
    samba_voc:
      building: "building"
      zone: "zone"
    samba_nox:
      building: "building"
      zone: "zone"
    samba_lux:
      building: "building"
      zone: "zone"
    samba_spl:
      building: "building"
      zone: "zone"

  # Define Influx field keys
  field_names:
    samba_temperature: "degrees"
    samba_humidity: "percent"
    samba_globe: "degrees"
    samba_airspeed: "m/s"
    samba_co2: "ppm"
    samba_pm25: "ug/m3"
    samba_voc: "ppb"
    samba_nox: "index"
    samba_lux: "lux"
    samba_spl: "dba"


# Include placeholder binary_sensor
binary_sensor:
