# SAMBA v2 FIRMWARE
# configure status LED and ligh effects
# https://esphome.io/components/light/esp32_rmt_led_strip.html
# written by Thomas Parkinson, May 2024


# Define LED component
light:
  - platform: esp32_rmt_led_strip
    id: samba_led
    rgb_order: GRB
    pin: GPIO27
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812

    # Define LED effects
    effects:
      - pulse:
          name: "slow_pulse"
          transition_length: 500ms
          update_interval: 1s
          max_brightness: 0.25
      - strobe:
          name: "alert_strobe"
          colors:
            - state: true
              brightness: 0.5
              red: 1.0
              green: 0.0
              blue: 0.0
              duration: 450ms
            - state: false
              duration: 100ms
            - state: true
              brightness: 0.5
              red: 1.0
              green: 0.0
              blue: 0.0
              duration: 450ms
            - state: false
              duration: 1000ms