# SAMBA v2 FIRMWARE
# configure over-the-air update support
# written by Thomas Parkinson, May 2024


# Enable OTA access
# https://esphome.io/components/ota.html
ota:
  - platform: esphome
    password: "${ota_password}"
    on_begin:
      then:
        - logger.log: 
            format: "Updating SAMBA through esphome"
            tag: "samba"
  - platform: http_request
    on_progress:
      then:
        - logger.log:
            format: "OTA progress: %0.1f%%"
            args: ["x"]
            level: INFO
            tag: "samba"

# Enable HTTP Request component for OTA and Influx
# https://esphome.io/components/http_request.html
http_request:
    id: http_client
    verify_ssl: false
    timeout: 10s
    watchdog_timeout: 8s

# Explicitly enable safe mode
# https://esphome.io/components/safe_mode
safe_mode:
  on_safe_mode:
    then:
      - logger.log: "Restoring SAMBA due to an unknown error"
      - light.turn_on:
          id: samba_led
          effect: slow_pulse
      - ota.http_request.flash:
          md5_url: http://github.com/IEQLab/samba/raw/main/restore/firmware.md5
          url: http://github.com/IEQLab/samba/raw/main/restore/firmware.ota.bin

