# SAMBA v2 FIRMWARE
# configure over-the-air update support
# written by Thomas Parkinson, May 2024


# Enable OTA access
# https://esphome.io/components/ota.html
ota:
  - platform: esphome
    password: "${ota_password}"
    on_begin:
      then:
        - logger.log: 
            format: "Updating SAMBA through esphome"
            tag: "samba"
  - platform: http_request
    on_progress:
      then:
        - logger.log:
            format: "OTA progress: %0.1f%%"
            args: ["x"]
            level: INFO
            tag: "samba"

# Enable managed updates
# https://esphome.io/components/update/http_request.html#
update:
  - platform: http_request
    id: fw_update
    name: "Firmware"
    source: http://github.com/IEQLab/samba/raw/main/manifest.json
    disabled_by_default: true

# Enable HTTP Request component for OTA and Influx
# https://esphome.io/components/http_request.html
http_request:
    id: http_client
    verify_ssl: true
    timeout: 8s
    watchdog_timeout: 10s

# Explicitly enable safe mode
# https://esphome.io/components/safe_mode
safe_mode:
  on_safe_mode:
    then:
      - logger.log: "Restoring SAMBA due to an unknown error"
      - light.turn_on:
          id: samba_led
          effect: slow_pulse
      - ota.http_request.flash:
          md5_url: http://github.com/IEQLab/samba/raw/main/restore/firmware.md5
          url: http://github.com/IEQLab/samba/raw/main/restore/firmware.ota.bin

# Define script to scatter friwmare update checks
script:
  - id: fw_check
    mode: restart
    then:
      # Add 0-15 minute jitter
      - lambda: |-
          uint32_t jitter_ms = esp_random() % (15 * 60 * 1000);
          ESP_LOGI("update", "Weekly update check; jitter = %u ms", jitter_ms);
          delay(jitter_ms);
      - component.update: fw_update
      - if:
          condition:
            update.is_available: fw_update
          then:
            - logger.log: "Update available; starting OTA"
            - update.perform:
                id: fw_update
          else:
            - logger.log: "No update available"
      - component.suspend: fw_update

