# SAMBA v2 FIRMWARE
# configure particulate matter sensor
# https://esphome.io/components/sensor/pmsx003.html
# written by Thomas Parkinson, May 2024


# Define sensor
sensor:
  - platform: pmsx003
    type: PMS5003T
    uart_id: uart_pm
    pm_2_5:
      id: pms_pm25
      internal: true
      filters:
        - filter_out: nan
        - clamp:
            min_value: 0
            max_value: 1000
            ignore_out_of_range: true
        - median:
            window_size: 300
            send_every: 30
            send_first_at: 10
    temperature:
      id: pms_temp
      internal: true
    humidity:
      id: pms_rh
      internal: true
      filters:
        - clamp:
            min_value: 0
            max_value: 100
            ignore_out_of_range: true
        - median:
            window_size: 300

# Define PM2.5 measurements
  - platform: template
    id: samba_pm25
    name: "PM2.5"
    update_interval: never
    accuracy_decimals: 0
    device_class: pm25
    unit_of_measurement: "µg/m3"
    icon: mdi:molecule
    lambda: |-
    
    lambda: |-
    
      float pm = id(pms_pm25).state;
      float rh = id(pms_rh).state;
      
      if (pm < 30.0) {
        return (0.524 * pm - 0.0862 * rh + 5.75);
      }
      
      else if (pm < 50.0) {
        float alpha = pm / 20.0 - 1.5;
        return (0.786 * alpha + 0.524 * (1.0 - alpha)) * pm - 0.0862 * rh + 5.75;
      }
      
      else if (pm < 210.0) {
        return (0.786 * pm - 0.0862 * rh + 5.75);
      }
      
      else if (pm < 260.0) {
        float alpha = pm / 50.0 - 4.2;
        return (0.69 * alpha + 0.786 * (1.0 - alpha)) * pm
               - 0.0862 * rh * (1.0 - alpha)
               + 2.966 * alpha
               + 5.75 * (1.0 - alpha)
               + 8.84e-4 * pm * pm * alpha;
      }
      
      else {
        return 2.966 + 0.69 * pm + 8.84e-4 * pm * pm;
      }
