# SAMBA v2 FIRMWARE
# configure real time clock, SNTP sync, and sample loop
# written by Thomas Parkinson, May 2024


# Define RTC device
# https://esphome.io/components/time/ds1307.html
time:
  - platform: ds1307
    id: ds1307_time
    address: 0x68
    update_interval: 1h
    
# Only create log file on sd card after time has been synced
    on_time_sync:
      then:
        - if:
            condition:
              lambda: 'return !id(sd_logfile);'
            then:
              - script.execute: sd_create
              - lambda: 'id(sd_logfile) = true;'

# Define loop for sensor measurements
# https://esphome.io/guides/automations.html#component-update-action
    on_time:
      - seconds: 0
        minutes: /5
        then:
          - script.execute: sensor_sample
      - days_of_week: SUN
        hours: 4
        minutes: 0
        seconds: 0
        then:
          - if:
              condition:
                time.has_time: 
                  id: sntp_time
              then:
                - delay: 300ms
                - ds1307.write_time:
                    id: ds1307_time
                - logger.log:
                    level: INFO
                    tag: "samba"
                    format: "RTC updated from SNTP"
              else:
                - logger.log:
                    level: WARN
                    tag: "samba"
                    format: "SNTP invalid – skipping RTC update"
      - days_of_week: MON
        hours: 4
        minutes: 0
        seconds: 0
        then:
          - script.execute: fw_check

# use SNTP server to set RTC time
  - platform: sntp
    id: sntp_time
    timezone: "Etc/GMT"
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    on_time_sync:
      then:
        - ds1307.write_time:
            id: ds1307_time
        - logger.log:
            level: INFO
            format: "SNTP time synchronised"
