# SAMBA v2 FIRMWARE
# Set subtitutions for individual configurations
# written by Thomas Parkinson, June 2025


# Define substitutions for configuration
# https://esphome.io/components/substitutions.html#command-line-substitutions
substitutions:
  
  # networking
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  enterprise_ssid: !secret enterprise_ssid
  enterprise_user: !secret enterprise_user
  enterprise_password: !secret enterprise_password
  enterprise_ttls: !secret enterprise_ttls
  
  # updates
  ota_password: !secret ota_password
  
  # Influx config
  influx_host: !secret influx_host
  influx_port: !secret influx_port
  influx_token: !secret influx_token
  influx_org: !secret influx_org
  influx_bucket: !secret influx_bucket
