# SAMBA v2 FIRMWARE
# configure wireless connections
# https://esphome.io/components/wifi.html
# written by Thomas Parkinson, May 2024


# Configure wifi networks
wifi:
  # Networks are set through the captive portal, never compiled in
  ap: {}
  power_save_mode: none
  output_power: 10.0 dB
  min_auth_mode: WPA
  reboot_timeout: 0s

# Direct user to WiFi portal
captive_portal:
