# SAMBA v2 FIRMWARE
# configure RTC device on SAMBA
# written by Thomas Parkinson, May 2024


# Define RTC device
# https://esphome.io/components/time/ds1307.html
time:
  - platform: ds1307
    id: ds1307_time
    address: 0x68
    update_interval: never

# Define loop for sensor measurements
# https://esphome.io/guides/automations.html#component-update-action
    on_time:
      - seconds: 0
        minutes: /5
        then:
          - script.execute: sensor_sample

# use SNTP server to set RTC time
  - platform: sntp
    id: sntp_time
    timezone: "Australia/Sydney"
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    on_time_sync:
      then:
        - ds1307.write_time:
            id: ds1307_time
        - logger.log:
            level: INFO
            format: "RTC synchronised with SNTP"

# Define timestamp sensor
# https://esphome.io/components/text_sensor/index.html
# TODO: use this instead https://esphome.io/components/datetime/#config-datetime
text_sensor:
  - platform: template
    id: sys_time
    name: "System Time"
    internal: true
    lambda: |-
      auto time_str = id(ds1307_time).now().strftime("%Y-%m-%d %H:%M:%S");
      return { time_str };
