# SAMBA v2 FIRMWARE
# configure diagnostic sensors on SAMBA
# written by Thomas Parkinson, May 2024


# Report the WiFi signal strength/RSSI in dB
# https://esphome.io/components/sensor/wifi_signal.html
sensor:
  - platform: wifi_signal
    id: wifi_signal_db
    name: "WiFi Signal dB"
    update_interval: 300s
    accuracy_decimals: 0
    device_class: signal_strength
    icon: "mdi:wifi-strength-3"
    entity_category: "diagnostic"

# Report the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    accuracy_decimals: 0
    unit_of_measurement: "%"
    device_class: signal_strength
    icon: "mdi:wifi-strength-3"
    entity_category: "diagnostic"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);

# Report the duraiton of time the device has been up for
  - platform: uptime
    id: device_uptime
    name: "Device Uptime"
    update_interval: 300s
    accuracy_decimals: 0
    device_class: duration
    icon: "mdi:clock-check-outline"
    entity_category: "diagnostic"

# Report the available memory
  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: "Available Memory"
    update_interval: 300s
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"

# Report network information
# https://esphome.io/components/text_sensor/wifi_info.html
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      update_interval: 900s
      entity_category: "diagnostic"
      icon: "mdi:ip-network-outline"
    ssid:
      name: "Connected SSID"
      update_interval: 900s
      entity_category: "diagnostic"
      icon: "mdi:wifi-check"
    mac_address:
      name: "Mac Address"
      entity_category: "diagnostic"
      icon: "mdi:wifi-check"

    