# SAMBA v2 FIRMWARE
# configure light sensor on SAMBA
# written by Thomas Parkinson, May 2024


# Define TSL2591 device
# https://esphome.io/components/sensor/tsl2591.html
sensor:
  - platform: tsl2591
    address: 0x29
    update_interval: 10s
    gain: auto
    device_factor: 53
    glass_attenuation_factor: 14.4
    calculated_lux:
      id: tsl_lux
      internal: true
      filters:
        - clamp:
            min_value: 0
            max_value: 10000
            ignore_out_of_range: true
        - median:
            window_size: 30
            send_every: 3
            send_first_at: 3
    actual_gain:
      id: tsl_gain
      internal: true
    visible:
      id: tsl_vis
      internal: true
    infrared:
      id: tsl_ir
      internal: true
    full_spectrum:
      id: tsl_full
      internal: true

# illuminance sensor
  - platform: template
    id: sensor_lux
    name: "Illuminance"
    update_interval: never
    accuracy_decimals: 0
    device_class: illuminance
    icon: "mdi:sun-wireless-outline"
    lambda: |-
      return id(tsl_lux).state;

