# SAMBA v2 FIRMWARE
# configure light sensor on SAMBA
# written by Thomas Parkinson, May 2024


# Lux sensor
# https://esphome.io/components/sensor/tsl2591.html
sensor:
  - platform: tsl2591
    address: 0x29
    update_interval: 10s
    gain: auto
    device_factor: 53
    glass_attenuation_factor: 14.4
    calculated_lux:
      id: tsl_lux
      name: "Illuminance"
      accuracy_decimals: 0
      device_class: illuminance
      icon: "mdi:sun-wireless-outline"
      filters:
        - median:
            window_size: 30
            send_every: 30
            send_first_at: 30
    actual_gain:
      id: "tsl_gain"
      name: "TSL2591 actual gain"
      internal: true
    visible:
      name: "TSL2591 visible light"
      internal: true
    infrared:
      name: "TSL2591 infrared light"
      internal: true
    full_spectrum:
      name: "TSL2591 full spectrum light"
      internal: true

## VEML7700 lux sensor
# https://esphome.io/components/sensor/veml7700.html
